RESOURCE-198 SQL SSL Cert
inspec/inspec-gcp pull request #399
Opened 2022-03-02 11:56 UTC by sa-progress

Signed-off-by: sa-progress <samir.anand@progress.com>

### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec GCP](https://github.com/inspec/inspec-gcp/CONTRIBUTING.md) document before 
submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant.

Please ensure commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2022-03-07 05:57 UTC, soumyo13 approved these changes

2022-03-07 06:01 UTC, soumyo13 requested changes

2022-03-07 06:01 UTC, soumyo13 commented on test/integration/verify/controls/google_sql_ssl_certs.rb
> +sql_connect = attribute('sql_connect', default: {
```suggestion
gcp_project_id = attribute(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')
sql_connect = attribute('sql_connect', value: {
```

2022-03-07 06:01 UTC, soumyo13 commented on docs/resources/google_sql_ssl_certs.md
> +A `google_sql_ssl_certs` is used to test a Google SslCert resource
```suggestion
A `google_sql_ssl_certs` is used to test a Google SslCerts resource
```

2022-03-07 06:02 UTC, soumyo13 commented
Please make the following changes as default is depreciated.

2022-03-14 04:55 UTC, soumyo13 commented on test/integration/verify/controls/google_sql_ssl_certs.rb
> +gcp_project_id = attribute(:gcp_project_id, value: 'gcp_project_id', description: 'The GCP project identifier.')
```suggestion
gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
```

2022-03-14 04:56 UTC, soumyo13 commented on test/integration/verify/controls/google_sql_ssl_certs.rb
> +sql_connect = attribute('sql_connect', value: {
```suggestion
sql_connect = attribute('sql_connect', default: {
```

2022-03-14 04:58 UTC, soumyo13 commented on test/integration/verify/controls/google_sql_ssl_cert.rb
> +sql_connect = attribute('sql_connect', value: {
```suggestion
gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
sql_connect = attribute('sql_connect', default: {
```

2022-03-14 04:59 UTC, sa-progress commented on test/integration/verify/controls/google_sql_ssl_cert.rb
> +sql_connect = attribute('sql_connect', default: {
Please revert back.Can change it manually.

2022-03-14 04:59 UTC, soumyo13 approved these changes

2022-03-14 05:45 UTC, merged